- name: "Check {{ STAKER }}-* exists"
  become: yes
  become_user: "{{ service }}"
  shell: "ag-cosmos-helper keys show --keyring-backend=test -a {{ STAKER }}-{{ inventory_hostname }}"
  ignore_errors: true
  register: staker_exists

- name: "Create {{ STAKER }}-*"
  become_user: "{{ service }}"
  become: true
  shell: "ag-cosmos-helper keys add --keyring-backend=test {{ staker }}"
  vars:
    staker: "{{ STAKER }}-{{ inventory_hostname }}"
  when: inventory_hostname != STAKER_NODE and staker_exists.rc != 0

- name: "Check {{ STAKER }}-* exists"
  become: yes
  become_user: "{{ service }}"
  shell: "ag-cosmos-helper keys show --keyring-backend=test -a {{ STAKER }}-{{ inventory_hostname }}"
  register: staker_address

- name: "Transfer {{ STAKER_AMOUNT }} to {{ STAKER }}-*"
  delegate_to: localhost
  shell: "\
    ag-cosmos-helper --home={{ SETUP_HOME + '/../faucet' }} \
     tx bank send faucet {{ staker_address.stdout }} {{ STAKER_AMOUNT }} \
      --node=tcp://{{ hostvars[STAKER_NODE]['ansible_host'] }}:26657 --keyring-backend=test --chain-id={{ CHAIN_NAME }} \
      --broadcast-mode=block --yes"
  vars:
    staker: "{{ STAKER }}-{{ inventory_hostname }}"
  when: inventory_hostname != STAKER_NODE

- name: "Create validators for {{ STAKER }}-*"
  become_user: "{{ service }}"
  become: true
  shell: "\
    ag-cosmos-helper tx staking create-validator --keyring-backend=test \
      --chain-id={{ CHAIN_NAME }} --amount={{ STAKER_AMOUNT }} \
      --moniker={{ moniker | default(inventory_hostname) }} --pubkey={{ valconspub }} \
      {{ (website | default(None)) and '--website=' ~ website }} \
      {{ (identity | default(None)) and '--identity=' ~ identity }} \
      --commission-rate=0.1 --commission-max-rate=0.2 --commission-max-change-rate=0.01 \
      --min-self-delegation=1 --broadcast-mode=block --from={{ staker }} --yes"
  vars:
    staker: "{{ STAKER }}-{{ inventory_hostname }}"
    valconspub: "{{ lookup('file', data + '/' + inventory_hostname + '/pubkey') }}"
  when: inventory_hostname != STAKER_NODE
