---

- hosts: "{{ STAKER_NODE }}"
  user: root
  strategy: free
  vars:
    - data: "{{ SETUP_HOME }}/{{ service }}/data"
    - service: ag-chain-cosmos
    - BOOTSTRAP_TOKENS: "{{ lookup('file', SETUP_HOME + '/boot-tokens.txt') }},100provisionpass"
    - CHAIN_NAME: "{{ lookup('file', SETUP_HOME + '/ag-chain-cosmos/chain-name.txt') }}"
    - NETWORK_CONFIG_URL: https://testnet.agoric.com/network-config
    - STAKER: ag-staker
    - STAKER_TOKENS: 10000000000000000000000000uagstake
    - STAKER_AMOUNT: 50000000uagstake
    - STAKER_NODE: validator0
  roles:
    - cosmos-genesis
