name: Notify Github Actions status via email
description: 'Notify on actions status'

inputs:
  from:
    description: 'The email address to send the notification from'
    required: false
  to:
    description: 'Recipients'
    required: false
  password:
    description: 'Sendgrid Password'
    required: false
  webhook:
    description: 'Slack webhook URL'
    required: true

runs:
  using: composite
  steps:
    - name: send ${{ job.status }} email
      if: ${{ inputs.to != '' }}
      uses: dawidd6/action-send-mail@v3
      with:
        # mail server settings
        server_address: smtp.sendgrid.net
        server_port: 465
        # user credentials
        username: apikey
        password: ${{ inputs.password }}
        # email subject
        subject: 'CI ${{ job.status }} in ${{ github.repository }} (job: ${{ github.job }})'
        # email body as text
        body: |-
          Job ${{ github.job }} in workflow ${{ github.workflow }} of ${{ github.repository }} status ${{ job.status }}

          Please take discussion to #ops-engineering

          Details at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        # comma-separated string, send email to
        to: ${{ inputs.to }}
        # from email name
        from: ${{ inputs.from }}
    - name: Send GitHub trigger payload
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "Job ${{ github.job }} in workflow ${{ github.workflow }} of ${{ github.repository }} status ${{ job.status }}\nDetails at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "username": "GitHub"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
