- name: "Create exported-genesis.json"
  become: yes
  become_user: "{{ service }}"
  shell: "{{ service }} export --for-zero-height > /home/{{ service }}/exported-genesis.json"

- name: "Fetch {{ exported | default('exported') }}/*/exported-genesis.json"
  fetch:
    dest: "{{ exported | default('exported') }}/{{ inventory_hostname }}/"
    flat: yes
    src: "/home/{{ service }}/exported-genesis.json"
