- name: "Check for {{ service }} private key"
  stat:
    path: "/home/{{ service }}/.{{ service }}/config/priv_validator_key.json"
  register: valkey

- name: "Reset {{ service }}"
  become: yes
  become_user: "{{ service }}"
  shell: "{{ service }} unsafe-reset-all"
  when:
    - valkey.stat.exists

- name: "Remove gentxs (they are signed incorrectly)"
  file:
    path: "/home/{{ service }}/.{{ service }}/config/gentx"
    state: absent

- name: "Remove genesis.json (needs to be regenerated)"
  file:
    path: "/home/{{ service }}/.{{ service }}/config/genesis.json"
    state: absent

- name: "Initialize {{ service }}"
  become: yes
  become_user: "{{ service }}"
  shell: "{{ service }} init --overwrite {{ inventory_hostname }} --chain-id={{ CHAIN_NAME }}"
