- name: "Ensure /home/{{ service }}/.{{ service }} exists"
  become_user: "{{ service }}"
  become: true
  file:
    path: "/home/{{ service }}/.{{ service }}"
    state: directory
    mode: 0755

- name: "Install {{ data | default(service + '/data') }}/../../ag-chain-cosmos/data/genesis.json"
  become_user: "{{ service }}"
  become: true
  copy:
    src: "{{ data | default(service + '/data') }}/../../ag-chain-cosmos/data/genesis.json"
    dest: "/home/{{ service }}/.{{ service }}/wwwroot/{{ CHAIN_NAME }}/genesis.json"
    owner: "{{ service }}"
    group: "{{ service }}"
    mode: 0644
    
- name: "Install {{ data | default(service + '/data') }}/cosmos-chain.json"
  become_user: "{{ service }}"
  become: true
  copy:
    src: "{{ data | default(service + '/data') }}/cosmos-chain.json"
    dest: "/home/{{ service }}/.{{ service }}/wwwroot/{{ CHAIN_NAME }}/chain.json"
    owner: "{{ service }}"
    group: "{{ service }}"
    mode: 0644

- name: "Set wwwroot/current to {{ CHAIN_NAME }}"
  become_user: "{{ service }}"
  become: true
  file:
    state: link
    path: "/home/{{ service }}/.{{ service }}/wwwroot/current"
    src: "{{ CHAIN_NAME }}"

- name: "Add {{ NETWORK_NAME }} keys"
  synchronize:
    src: "{{ SETUP_HOME }}/{{ NETWORK_NAME }}.{{ item }}"
    dest: "/home/{{ service }}/.{{ service }}/{{NETWORK_NAME}}.{{item}}"
    mode: push
  with_items:
    - crt
    - key
  when:
    - tlscrt.stat.exists
    - tlskey.stat.exists
