- name: "Ensure /home/{{ service }}/.ag-pserver/wwwroot/{{ CHAIN_NAME }} exists"
  become: yes
  become_user: "{{ service }}"
  file:
    path: "/home/{{ service }}/.ag-pserver/wwwroot/{{ CHAIN_NAME }}"
    state: directory

- name: "Create provisioning mnemonic"
  delegate_to: localhost
  shell:
    cmd: "ag-cosmos-helper keys mnemonic 2>&1 | tee provisioning-mnemonic.txt"
    chdir: "{{ SETUP_HOME }}"
  register: mnemonic

- name: "Delete {{ service }} ag-solo key"
  become: yes
  become_user: "{{ service }}"
  shell:
    cmd: "ag-cosmos-helper --home=/home/{{ service }}/.ag-pserver/ag-cosmos-helper-statedir --keyring-backend=test keys delete ag-solo --yes"
    removes: "/home/{{ service }}/.ag-pserver/ag-cosmos-helper-statedir"
  ignore_errors: yes

- name: "Create {{ service }} ag-solo key"
  become: yes
  become_user: "{{ service }}"
  shell:
    cmd: "ag-cosmos-helper --home=/home/{{ service }}/.ag-pserver/ag-cosmos-helper-statedir --keyring-backend=test keys add --recover ag-solo"
    stdin: "{{ mnemonic.stdout }}"

- name: "Create ag-cosmos-helper-address"
  become: yes
  become_user: "{{ service }}"
  shell:
    cmd: "ag-cosmos-helper --home=/home/{{ service }}/.ag-pserver/ag-cosmos-helper-statedir \
      --keyring-backend=test keys show -a ag-solo > /home/{{ service }}/.ag-pserver/ag-cosmos-helper-address"
