name: Integration tests

on:
 push:
   branches: [master]
 pull_request:

jobs:
  # This job is meant to emulate what developers working with the Agoric platform will experience
  # It should be kept in sync with https://agoric.com/documentation/getting-started/
  getting-started:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

# Prerequisites

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # 'yarn install' must be done at the top level, to build all the
    # cross-package symlinks
    - run: yarn install
    - run: yarn build
    - run: yarn link-cli ~/bin/agoric

    - name: run agoric-cli integration-test
      working-directory: ./packages/agoric-cli
      run: PATH="$PATH:$HOME/bin" yarn integration-test
